
FROM python:3.9


WORKDIR /code


COPY ./requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


COPY ./main_data_api.py ./test.py /code/


# CMD ["fastapi", "run", "main_data_api.py", "--port", "80", "--reload"]